//
// File.swift
// Erichood
//
// Created by Jiahao Zhang on 11/20/16.
// Copyright © 2016 Jiahao Zhang. All rights reserved.
//

import Foundation

let file = "ABUS>>BBY>>CDI>>EGRX>>EPC>>FORM>>HMLP>>LHCG>>MRIN>>NRP>>OCN>>SCHW>>TRP>>ANW>>CRNT>>FAF>>MRCY>>RST>>WFBI>>FOR>>SKYW>>ACIA>>ARCW>>ASUR>>NMM>>THO>>Y>>BBL>>KNSL>>MSGN>>NVDA>>PFIE>>RDI>>SOUHY>>SNC>>UPLD>>WCG>>ATHX>>CGNT>>COTV>>ENS>>EVDY>>FF>>IGT>>KNMCY>>EDU>>OTIV>>SCMP>>TX>>ADUS>>ARTX>>BRKS>>TCS>>CUTR>>FANG>>FN>>KRO>>LMCA>>MGLN>>MGM>>MCHP>>RUN>>ACGL>>CC>>NMIH>>SRT>>TLP>>MITT>>AAOI>>CARB>>FMC>>LMCK>>SABR>>STMP>>UBNT>>CIB>>CGNX>>COHR>>CTRL>>HIIQ>>INVVY>>KE>>KVHI>>LVS>>DLAKY>>MRVL>>MFA>>NCI>>SAJA>>USDP>>WMC>>WDC>>WLDN>>CBM>>PLUS>>FRBA>>FOXF>>HLUYY>>IL>>KEM>>MPEL>>MCY>>NOA>>PMT>>RYN>>STWD>>VLEEY>>VNDA>>AZUR>>CIM>>IDXX>>KNOP>>Q>>SCGLY>>TKC>>AEIS>>CODI>>EBMT>>HSKA>>HBAN>>IPHS>>LUK>>NOC>>ACTG>>AHGP>>AMRC>>ATNI>>CRUS>>EA>>LOGM>>NXTM>>CDE>>EME>>ROCK>>ISTR>>LTRX>>SSD>>SJW>>TER>>TTMI>>VRSN>>CBU>>GNRC>>NSIT>>JBT>>PUB>>ALSN>>ALDW>>BAX>>CLGX>>LFUS>>MCS>>MKSI>>PKX>>UPMKY>>ACRE>>BAK>>EFSC>>HMST>>PPRUY>>LAWS>>MDR>>MCRI>>NVEC>>WTKWY>>ANCX>>ACCO>>SXC>>CSFL>>DPZ>>SASR>>STX>>TSC>>CRMT>>CARO>>CPRT>>LRCX>>LPLA>>OLBK>>LTXB>>MSBHY>>OSB>>WF>>KOP>>AKO.B>>SMP>>VOXX>>ORIG>>ARLP>>CLD>>NDEKY>>VRTS>>AAAP>>SINA>>TSM>>BHP>>KYO>>CASH>>RIO>>SF>>KNCAY>>TOELY>>MELI>>UCTT>>UPLMQ>>WOR>>JBL>>AHCHY>>FFKT>>SITO>>CPA>>ITRI>>JCAP>>GWPH>>SAFM>>EGL>>SKM>>KT"
